// country option  
export const countryOptions = [
    { value: "+1", label: "+1(USA)" },
    { value: "+44", label: "+44(UK)" },
    { value: "+91", label: "+91(India)" },
    { value: "+61", label: "+61(Australia)" },
    { value: "+81", label: "+81(Japan)" },
    { value: "+49", label: "+49(Germany)" },
    { value: "+86", label: "+86(China)" },
    { value: "+33", label: "+33(France)" },
    { value: "+39", label: "+39(Italy)" },
    { value: "+55", label: "+55(Brazil)" },
    { value: "+7", label: "+7(Russia)" },
    { value: "+34", label: "+34(Spain)" },
    { value: "+52", label: "+52(Mexico)" },
    { value: "+41", label: "+41(Switzerland)" },
    { value: "+64", label: "+64(New Zealand)" },
    { value: "+45", label: "+45(Denmark)" },
    { value: "+46", label: "+46(Sweden)" },
    { value: "+47", label: "+47(Norway)" },
    { value: "+48", label: "+48(Poland)" },
    { value: "+20", label: "+20(Egypt)" },
    { value: "+971", label: "+971(UAE)" },
    { value: "+966", label: "+966(Saudi Arabia)" },
    { value: "+27", label: "+27(South Africa)" },
    { value: "+351", label: "+351(Portugal)" },
    { value: "+82", label: "+82(South Korea)" },
];



// State options based on the selected country
export const stateOptions = {
    "+1": [
        { value: "California", label: "California" },
        { value: "Texas", label: "Texas" },
        { value: "New York", label: "New York" },
        { value: "Florida", label: "Florida" },
        { value: "Illinois", label: "Illinois" },
    ],
    "+44": [
        { value: "London", label: "London" },
        { value: "Manchester", label: "Manchester" },
    ],
    "+91": [
        { value: "Andhra Pradesh", label: "Andhra Pradesh" },
        { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
        { value: "Assam", label: "Assam" },
        { value: "Bihar", label: "Bihar" },
        { value: "Chhattisgarh", label: "Chhattisgarh" },
        { value: "Goa", label: "Goa" },
        { value: "Gujarat", label: "Gujarat" },
        { value: "Haryana", label: "Haryana" },
        { value: "Himachal Pradesh", label: "Himachal Pradesh" },
        { value: "Jharkhand", label: "Jharkhand" },
        { value: "Karnataka", label: "Karnataka" },
        { value: "Kerala", label: "Kerala" },
        { value: "Madhya Pradesh", label: "Madhya Pradesh" },
        { value: "Maharashtra", label: "Maharashtra" },
        { value: "Manipur", label: "Manipur" },
        { value: "Meghalaya", label: "Meghalaya" },
        { value: "Mizoram", label: "Mizoram" },
        { value: "Nagaland", label: "Nagaland" },
        { value: "Odisha", label: "Odisha" },
        { value: "Punjab", label: "Punjab" },
        { value: "Rajasthan", label: "Rajasthan" },
        { value: "Sikkim", label: "Sikkim" },
        { value: "Tamil Nadu", label: "Tamil Nadu" },
        { value: "Telangana", label: "Telangana" },
        { value: "Tripura", label: "Tripura" },
        { value: "Uttar Pradesh", label: "Uttar Pradesh" },
        { value: "Uttarakhand", label: "Uttarakhand" },
        { value: "West Bengal", label: "West Bengal" },
    ],
    "+61": [
        { value: "New South Wales", label: "New South Wales" },
        { value: "Victoria", label: "Victoria" },
    ],
    "+81": [
        { value: "Tokyo", label: "Tokyo" },
        { value: "Osaka", label: "Osaka" },
    ],
};

// City options based on selected state and country
export const cityOptions = {
    "+1": {
        California: [
            { value: "Los Angeles", label: "Los Angeles" },
            { value: "San Francisco", label: "San Francisco" },
            { value: "San Diego", label: "San Diego" },
            { value: "Sacramento", label: "Sacramento" },
            { value: "Long Beach", label: "Long Beach" },
        ],
        Texas: [
            { value: "Dallas", label: "Dallas" },
            { value: "Houston", label: "Houston" },
            { value: "Austin", label: "Austin" },
            { value: "San Antonio", label: "San Antonio" },
            { value: "Fort Worth", label: "Fort Worth" },
        ],
        "New York": [
            { value: "New York City", label: "New York City" },
            { value: "Buffalo", label: "Buffalo" },
            { value: "Rochester", label: "Rochester" },
            { value: "Syracuse", label: "Syracuse" },
            { value: "Albany", label: "Albany" },
        ],
        Florida: [
            { value: "Miami", label: "Miami" },
            { value: "Orlando", label: "Orlando" },
            { value: "Tampa", label: "Tampa" },
            { value: "Jacksonville", label: "Jacksonville" },
            { value: "Tallahassee", label: "Tallahassee" },
        ],
        Illinois: [
            { value: "Chicago", label: "Chicago" },
            { value: "Aurora", label: "Aurora" },
            { value: "Naperville", label: "Naperville" },
            { value: "Joliet", label: "Joliet" },
            { value: "Rockford", label: "Rockford" },
        ],
    },
    "+44": {
        London: [
            { value: "Westminster", label: "Westminster" },
            { value: "Camden", label: "Camden" },
            { value: "Islington", label: "Islington" },
            { value: "Hackney", label: "Hackney" },
            { value: "Chelsea", label: "Chelsea" },
        ],
        Manchester: [
            { value: "Northern Quarter", label: "Northern Quarter" },
            { value: "Deansgate", label: "Deansgate" },
            { value: "Chorlton", label: "Chorlton" },
            { value: "Salford", label: "Salford" },
            { value: "Didsbury", label: "Didsbury" },
        ],
    },
    "+91": {
        "Andhra Pradesh": [
            { value: "Visakhapatnam", label: "Visakhapatnam" },
            { value: "Vijayawada", label: "Vijayawada" },
            { value: "Guntur", label: "Guntur" },
            { value: "Nellore", label: "Nellore" },
            { value: "Tirupati", label: "Tirupati" },
        ],
        "Arunachal Pradesh": [
            { value: "Itanagar", label: "Itanagar" },
            { value: "Naharlagun", label: "Naharlagun" },
            { value: "Pasighat", label: "Pasighat" },
        ],
        Assam: [
            { value: "Guwahati", label: "Guwahati" },
            { value: "Dibrugarh", label: "Dibrugarh" },
            { value: "Jorhat", label: "Jorhat" },
            { value: "Silchar", label: "Silchar" },
        ],
        Bihar: [
            { value: "Patna", label: "Patna" },
            { value: "Gaya", label: "Gaya" },
            { value: "Bhagalpur", label: "Bhagalpur" },
            { value: "Muzaffarpur", label: "Muzaffarpur" },
        ],
        Chhattisgarh: [
            { value: "Raipur", label: "Raipur" },
            { value: "Bilaspur", label: "Bilaspur" },
            { value: "Korba", label: "Korba" },
            { value: "Raigarh", label: "Raigarh" },
        ],
        Goa: [
            { value: "Panaji", label: "Panaji" },
            { value: "Vasco da Gama", label: "Vasco da Gama" },
            { value: "Margao", label: "Margao" },
        ],
        Gujarat: [
            { value: "Ahmedabad", label: "Ahmedabad" },
            { value: "Surat", label: "Surat" },
            { value: "Vadodara", label: "Vadodara" },
            { value: "Rajkot", label: "Rajkot" },
        ],
        Haryana: [
            { value: "Gurugram", label: "Gurugram" },
            { value: "Faridabad", label: "Faridabad" },
            { value: "Panipat", label: "Panipat" },
            { value: "Ambala", label: "Ambala" },
        ],
        "Himachal Pradesh": [
            { value: "Shimla", label: "Shimla" },
            { value: "Manali", label: "Manali" },
            { value: "Kullu", label: "Kullu" },
            { value: "Dharamshala", label: "Dharamshala" },
        ],
        Jharkhand: [
            { value: "Ranchi", label: "Ranchi" },
            { value: "Jamshedpur", label: "Jamshedpur" },
            { value: "Dhanbad", label: "Dhanbad" },
        ],
        Karnataka: [
            { value: "Bengaluru", label: "Bengaluru" },
            { value: "Mysuru", label: "Mysuru" },
            { value: "Hubli", label: "Hubli" },
            { value: "Mangalore", label: "Mangalore" },
        ],
        Kerala: [
            { value: "Thiruvananthapuram", label: "Thiruvananthapuram" },
            { value: "Kochi", label: "Kochi" },
            { value: "Kozhikode", label: "Kozhikode" },
            { value: "Thrissur", label: "Thrissur" },
        ],
        "Madhya Pradesh": [
            { value: "Bhopal", label: "Bhopal" },
            { value: "Indore", label: "Indore" },
            { value: "Gwalior", label: "Gwalior" },
            { value: "Ujjain", label: "Ujjain" },
        ],
        Maharashtra: [
            { value: "Mumbai", label: "Mumbai" },
            { value: "Pune", label: "Pune" },
            { value: "Nagpur", label: "Nagpur" },
            { value: "Nashik", label: "Nashik" },
            { value: "Aurangabad", label: "Aurangabad" },
        ],
        Manipur: [
            { value: "Imphal", label: "Imphal" },
            { value: "Thoubal", label: "Thoubal" },
        ],
        Meghalaya: [
            { value: "Shillong", label: "Shillong" },
            { value: "Tura", label: "Tura" },
        ],
        Mizoram: [
            { value: "Aizawl", label: "Aizawl" },
            { value: "Lunglei", label: "Lunglei" },
        ],
        Nagaland: [
            { value: "Kohima", label: "Kohima" },
            { value: "Dimapur", label: "Dimapur" },
        ],
        Odisha: [
            { value: "Bhubaneswar", label: "Bhubaneswar" },
            { value: "Cuttack", label: "Cuttack" },
            { value: "Rourkela", label: "Rourkela" },
            { value: "Berhampur", label: "Berhampur" },
        ],
        Punjab: [
            { value: "Chandigarh", label: "Chandigarh" },
            { value: "Amritsar", label: "Amritsar" },
            { value: "Ludhiana", label: "Ludhiana" },
            { value: "Jalandhar", label: "Jalandhar" },
        ],
        Rajasthan: [
            { value: "Jaipur", label: "Jaipur" },
            { value: "Udaipur", label: "Udaipur" },
            { value: "Jodhpur", label: "Jodhpur" },
            { value: "Kota", label: "Kota" },
        ],
        Sikkim: [{ value: "Gangtok", label: "Gangtok" }],
        "Tamil Nadu": [
            { value: "Chennai", label: "Chennai" },
            { value: "Coimbatore", label: "Coimbatore" },
            { value: "Madurai", label: "Madurai" },
            { value: "Trichy", label: "Trichy" },
        ],
        Telangana: [
            { value: "Hyderabad", label: "Hyderabad" },
            { value: "Warangal", label: "Warangal" },
            { value: "Khammam", label: "Khammam" },
        ],
        Tripura: [{ value: "Agartala", label: "Agartala" }],
        "Uttar Pradesh": [
            { value: "Lucknow", label: "Lucknow" },
            { value: "Kanpur", label: "Kanpur" },
            { value: "Agra", label: "Agra" },
            { value: "Varanasi", label: "Varanasi" },
            { value: "Ghaziabad", label: "Ghaziabad" },
            { value: "Noida", label: "Noida" },
            { value: "Aligarh", label: "Aligarh" },
            { value: "Bareilly", label: "Bareilly" },
            { value: "Meerut", label: "Meerut" },
            { value: "Mathura", label: "Mathura" },
            { value: "Moradabad", label: "Moradabad" },
            { value: "Firozabad", label: "Firozabad" },
            { value: "Sultanpur", label: "Sultanpur" },
            { value: "Shahjahanpur", label: "Shahjahanpur" },
            { value: "Rampur", label: "Rampur" },
            { value: "Muzaffarnagar", label: "Muzaffarnagar" },
            { value: "Jaunpur", label: "Jaunpur" },
            { value: "Raebareli", label: "Raebareli" },
            { value: "Unnao", label: "Unnao" },
            { value: "Hardoi", label: "Hardoi" },
        ],
        Uttarakhand: [
            { value: "Dehradun", label: "Dehradun" },
            { value: "Nainital", label: "Nainital" },
            { value: "Haridwar", label: "Haridwar" },
        ],
        "West Bengal": [
            { value: "Kolkata", label: "Kolkata" },
            { value: "Howrah", label: "Howrah" },
            { value: "Siliguri", label: "Siliguri" },
            { value: "Durgapur", label: "Durgapur" },
        ],
    },

    "+61": {
        "New South Wales": [
            { value: "Sydney", label: "Sydney" },
            { value: "Newcastle", label: "Newcastle" },
            { value: "Wollongong", label: "Wollongong" },
            { value: "Maitland", label: "Maitland" },
            { value: "Tweed Heads", label: "Tweed Heads" },
        ],
        Victoria: [
            { value: "Melbourne", label: "Melbourne" },
            { value: "Geelong", label: "Geelong" },
            { value: "Ballarat", label: "Ballarat" },
            { value: "Bendigo", label: "Bendigo" },
            { value: "Shepparton", label: "Shepparton" },
        ],
    },
    "+81": {
        Tokyo: [
            { value: "Shibuya", label: "Shibuya" },
            { value: "Shinjuku", label: "Shinjuku" },
            { value: "Akihabara", label: "Akihabara" },
            { value: "Asakusa", label: "Asakusa" },
            { value: "Roppongi", label: "Roppongi" },
        ],
        Osaka: [
            { value: "Namba", label: "Namba" },
            { value: "Umeda", label: "Umeda" },
            { value: "Tennoji", label: "Tennoji" },
            { value: "Kyobashi", label: "Kyobashi" },
            { value: "Suminoe", label: "Suminoe" },
        ],
    },
};